### ISSUE TITLE
Migration Django

### ISSUE THREAD

**Issue by Juknum** [ae-utbm/sith3#121]
In GitLab by @kov on Apr 29, 2022, 24:58

Since django 2.2 security support has ended since 1st august 2022, it's becoming urgent to migrate to a new django version.
I think we should aim for django 3.2 since it's the last LTS version.
I've created a new branch called [kov/django-migration](https://ae-dev.utbm.fr/ae/Sith/-/tree/kov/django-migration) where I'm currently migrating the project to django 3.0.
Once the project runs on 3.0 i'll be moving it to 3.2.

**Comment by klmp200** [comment]
Fixé :)
