### ISSUE TITLE
Glitching logo when buying on e-boutic

### ISSUE THREAD

**Issue by TheoDurr** [ae-utbm/sith3#487]
When validating basket on e-boutic, the following happens

![CleanShot 2022-11-12 at 10 17 24](https://user-images.githubusercontent.com/47631598/201467581-a5ff4566-0df8-41bc-a557-832e660c7a2d.gif)

Could you fix this before deploying to production please ? thanks

**Comment by imperosol** [comment]
J'arrive pas à reproduire.
