### ISSUE TITLE
Ajouter un feedback visuel lors de l'ajout d'un item dans le panier (mobile first)

### ISSUE THREAD

**Issue by TheoDurr** [ae-utbm/sith3#509]
Module : Eboutic
Orientation du développement : Front-end

# Problématique
Cette proposition concerne principalement les utilisateurs mobiles, qui ne voient pas le panier lorsqu'ils ajoutent un produit.

# Idée
Ajouter un feedback visuel pour indiquer à l'utilisateur que le produit a bien été ajouté au panier. On peut penser à une animation de ce style :

<img src="https://cdn.discordapp.com/attachments/1022572000553746452/1051968971034869900/92460-checkmark-animation.gif" width="200" height="200">

Elle aiderait grandement au feedback sur les actions de l'utilisateur, que ce soit sur desktop ou mobile.

**Comment by imperosol** [comment]
C'est une bonne idée. J'ai vu quelques personnes que ça perturbait, en effet.
J'imagine bien le fond du bouton qui devient vert et qui reprend progressivement sa couleur normale avec ton icône qui prend temporairement la place de l'image du produit.
