### ISSUE TITLE
Missing sith dependency

### ISSUE THREAD

**Issue by TheoDurr** [ae-utbm/sith3#524]
La dépendance `setuptools est manquante', elle est nécessaire pour la migration.

# Solution
Ajouter `setuptools`

**Comment by TheoDurr** [comment]
J'ai installé la dépendance côté système ça n'a rien changé. Installer la dépendance avec poetry a résolu le soucis

**Comment by klmp200** [comment]
Ok, dans ce cas il faut les deux
Sinon il ne doit pas correctement trouver la dépendance dans l'environnement
