### ISSUE TITLE
Remplacer Vue par Alpine pour les clics

### ISSUE THREAD

**Issue by imperosol** [ae-utbm/sith3#539]
Alpine est plus léger et plus adapté que Vue pour les besoins spécifiques du site. Il serait donc préférable de se recentrer vers Alpine pour le développement du site côté client.

Actuellement, Vue n'est utilisé que pour les clics, donc son remplacement ne devrait pas poser trop de problèmes.

**Comment by Juknum** [comment]
@imperosol c'est présent dans #558 ? vu que j'y ai vu du Alpine :eyes:

**Comment by imperosol** [comment]
> @imperosol c'est présent dans #558 ? vu que j'y ai vu du Alpine 👀

Absolument pas. Ca n'a rien à voir. dans cette PR, on a touché à l'eboutic, pas aux clics, et il n'y avait pas de VueJS avant là où Alpine est arrivé.
