### ISSUE TITLE
Durée depuis la dernière cotisation sur le profil utilisateur

### ISSUE THREAD

**Issue by TheoDurr** [ae-utbm/sith3#546]
Permet aux membres du bureau de l'ae de voir une durée plus claire depuis la dernière cotisation.

### Qui peut le voir ?
Les membres ayant la possibilité de gérer les cotisations.

### Où ?
Sur le profil de l'utilisateur, en complément du texte "_non cotisant_"

**Comment by Juknum** [comment]
Feature reportée à la v4
