### ISSUE TITLE
Optimiser le CI/CD du site actuel pour se faire la main avec les actions/workflow GitHub

### ISSUE THREAD

**Issue by Juknum** [ae-utbm/sith3#588]

**Comment by Nchrd** [comment]
J'ai trouvé ça qui devrait pouvoir marcher même avec poetry : [lien vers la doc django](https://docs.djangoproject.com/fr/4.2/ref/django-admin/#cmdoption-test-parallel)
Ca permet d'utiliser autant de coeur que la VM de git en a pour faire les test en parallèle

**Comment by Nchrd** [comment]
> En vrai c'est pas mal, faudra juste faire gaffe à ça :
> 
> > Chaque processus travaille avec sa propre base de données. Vous devez vous assurer que les différents cas de test n’accèdent pas aux mêmes ressources. **Par exemple, les cas de test qui touchent au système de fichiers devraient créer un répertoire temporaire pour leur propre usage.**

On a des limites de tailles en stockage pour les bases de données ? Je sais pas où est-ce qu'on trouve les specs des VM de Git
